# Generated by Django 4.2.5 on 2023-10-02 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost_price', models.PositiveSmallIntegerField(null=True)),
                ('wholesale_price', models.PositiveSmallIntegerField(null=True)),
                ('retail_price', models.PositiveSmallIntegerField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('stock', models.ManyToManyField(to='stock.stockmodel')),
                ('store_back', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_back', to='stock.storeback')),
                ('store_hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_hall', to='stock.storehall')),
                ('store_up', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_up', to='stock.storeup')),
            ],
        ),
    ]
