# Generated by Django 4.2.3 on 2023-07-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_goodsmodel_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveSmallIntegerField()),
                ('cost_price', models.PositiveSmallIntegerField()),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodsmodel')),
            ],
        ),
    ]
