# Generated by Django 4.2.3 on 2023-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_rename_datetime_countgoods_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countgoods',
            name='name',
        ),
        migrations.AddField(
            model_name='countgoods',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
