# Generated by Django 4.2.3 on 2023-08-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_remove_countgoods_name_countgoods_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countgoods',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
