# Generated by Django 4.2.3 on 2023-08-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_alter_countgoods_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countgoods',
            name='datetime',
            field=models.DateField(),
        ),
    ]
