# Generated by Django 4.2.3 on 2023-08-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_alter_countgoods_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountGoods',
        ),
    ]
