# Generated by Django 4.2.3 on 2023-08-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('goods', '0015_delete_countgoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='stock_id',
            field=models.ManyToManyField(to='stock.stockmodel'),
        ),
    ]
