# Generated by Django 4.2.3 on 2023-08-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_goodsmodel_stock_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsmodel',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
