# Generated by Django 4.2.3 on 2023-08-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_rename_stock_id_goodsmodel_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='cost_price',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
