# Generated by Django 4.2.3 on 2023-08-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_alter_goodsmodel_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='images',
            field=models.ImageField(default=11, upload_to='images'),
            preserve_default=False,
        ),
    ]
