# Generated by Django 4.2.3 on 2023-08-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_goodsmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
