# Generated by Django 4.2.3 on 2023-08-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0020_alter_goodsmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
