# Generated by Django 4.2.4 on 2023-08-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_alter_imagemodel_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
