# Generated by Django 4.2.4 on 2023-08-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_marketmodel'),
        ('goods', '0024_delete_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='market',
            field=models.ManyToManyField(to='stock.marketmodel'),
        ),
    ]
