# Generated by Django 4.2.4 on 2023-08-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0026_remove_goodsmodel_market_goodsmodel_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsmodel',
            name='market',
        ),
    ]
