# Generated by Django 4.2.4 on 2023-08-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_storeback_storehall_storeup'),
        ('goods', '0027_remove_goodsmodel_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='store_back',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_back', to='stock.storeback'),
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='store_hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_hall', to='stock.storehall'),
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='store_up',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_up', to='stock.storeup'),
        ),
    ]
