# Generated by Django 4.2.4 on 2023-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_marketmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmodel',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
