# Generated by Django 4.2.3 on 2023-08-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0015_delete_countgoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_now=True)),
                ('count', models.PositiveSmallIntegerField()),
                ('cost_price', models.PositiveSmallIntegerField()),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodsmodel')),
            ],
        ),
    ]
