# Generated by Django 4.2.4 on 2023-08-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_imagemodel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
