# Generated by Django 4.2.4 on 2023-09-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_imagemodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='name',
        ),
    ]
